import { Injectable, inject } from '@angular/core';
import { Timestamp, deleteDoc, doc, getDocs, query, serverTimestamp, setDoc, updateDoc } from 'firebase/firestore';
import { FIRESTORE } from '../../core/firebase/firebase.providers';
import { RecurringRule, RecurringRuleDraft } from '../../domain/models/recurring-rule';
import { userCollection, userItemDocument } from '../firestore-paths';

@Injectable({ providedIn: 'root' })
export class RecurringRuleRepository {
  private readonly firestore = inject(FIRESTORE);

  async listAll(uid: string): Promise<RecurringRule[]> {
    const snapshot = await getDocs(query(userCollection<RecurringRule>(this.firestore, uid, 'recurringRules')));
    return snapshot.docs.map((document) => document.data());
  }

  async create(uid: string, draft: RecurringRuleDraft): Promise<RecurringRule> {
    const reference = doc(userCollection<RecurringRule>(this.firestore, uid, 'recurringRules'));
    await setDoc(userItemDocument(this.firestore, uid, 'recurringRules', reference.id), {
      ...draft,
      createdAt: serverTimestamp(),
      updatedAt: serverTimestamp(),
    });
    return { ...draft, id: reference.id, createdAt: Timestamp.now(), updatedAt: Timestamp.now() };
  }

  async update(uid: string, id: string, changes: Partial<RecurringRuleDraft>): Promise<void> {
    await updateDoc(userItemDocument(this.firestore, uid, 'recurringRules', id), {
      ...changes,
      updatedAt: serverTimestamp(),
    });
  }

  /** Movements already generated by the rule stay in the history. */
  async remove(uid: string, id: string): Promise<void> {
    await deleteDoc(userItemDocument(this.firestore, uid, 'recurringRules', id));
  }
}
