import { Component, input } from '@angular/core';
import {
  LucideArchive,
  LucideArchiveRestore,
  LucideArrowDown,
  LucideArrowLeftRight,
  LucideArrowUp,
  LucideBanknote,
  LucideBriefcase,
  LucideCalendar,
  LucideCalendarClock,
  LucideCar,
  LucideChartColumn,
  LucideCheck,
  LucideChevronDown,
  LucideCircleAlert,
  LucideCircleCheck,
  LucideCircleUser,
  LucideCoins,
  LucideCopy,
  LucideCreditCard,
  LucideDownload,
  LucideDynamicIcon,
  LucideEllipsis,
  LucideFunnel,
  LucideGift,
  LucideHandCoins,
  LucideHeartPulse,
  LucideHouse,
  LucideInfo,
  LucideLandmark,
  LucideList,
  LucideLogOut,
  LucidePartyPopper,
  LucidePause,
  LucidePencil,
  LucidePiggyBank,
  LucidePlay,
  LucidePlus,
  LucideReceipt,
  LucideRefreshCw,
  LucideRepeat,
  LucideSearch,
  LucideSettings,
  LucideShare,
  LucideShoppingBag,
  LucideShoppingCart,
  LucideSmartphone,
  LucideSparkles,
  LucideSquarePlus,
  LucideStar,
  LucideTag,
  LucideTarget,
  LucideTrash,
  LucideTrendingDown,
  LucideTrendingUp,
  LucideTriangleAlert,
  LucideTv,
  LucideUndo2,
  LucideUpload,
  LucideWallet,
  LucideX,
  provideLucideIcons,
} from '@lucide/angular';

export const ICON_NAMES = [
  'arrow-down',
  'arrow-left-right',
  'arrow-up',
  'archive',
  'archive-restore',
  'banknote',
  'briefcase',
  'calendar',
  'calendar-clock',
  'car',
  'chart-column',
  'check',
  'chevron-down',
  'circle-alert',
  'circle-check',
  'circle-user',
  'coins',
  'copy',
  'credit-card',
  'download',
  'ellipsis',
  'funnel',
  'gift',
  'hand-coins',
  'heart-pulse',
  'house',
  'info',
  'landmark',
  'list',
  'log-out',
  'party-popper',
  'pause',
  'pencil',
  'piggy-bank',
  'play',
  'plus',
  'receipt',
  'refresh-cw',
  'repeat',
  'search',
  'settings',
  'share',
  'shopping-bag',
  'shopping-cart',
  'smartphone',
  'sparkles',
  'square-plus',
  'star',
  'tag',
  'target',
  'trash',
  'trending-down',
  'trending-up',
  'triangle-alert',
  'tv',
  'undo-2',
  'upload',
  'wallet',
  'x',
] as const;

export type IconName = (typeof ICON_NAMES)[number];

/** Icons that can be chosen for accounts and categories. */
export const SELECTABLE_ICONS: readonly IconName[] = [
  'wallet',
  'landmark',
  'credit-card',
  'banknote',
  'piggy-bank',
  'coins',
  'house',
  'shopping-cart',
  'car',
  'heart-pulse',
  'party-popper',
  'hand-coins',
  'tv',
  'shopping-bag',
  'receipt',
  'briefcase',
  'gift',
  'tag',
  'undo-2',
  'target',
  'ellipsis',
];

export function toIconName(value: string | undefined, fallback: IconName = 'ellipsis'): IconName {
  return (ICON_NAMES as readonly string[]).includes(value ?? '') ? (value as IconName) : fallback;
}

@Component({
  selector: 'app-icon',
  imports: [LucideDynamicIcon],
  providers: [
    provideLucideIcons(
      LucideArchive,
      LucideArchiveRestore,
      LucideArrowDown,
      LucideArrowLeftRight,
      LucideArrowUp,
      LucideBanknote,
      LucideBriefcase,
      LucideCalendar,
      LucideCalendarClock,
      LucideCar,
      LucideChartColumn,
      LucideCheck,
      LucideChevronDown,
      LucideCircleAlert,
      LucideCircleCheck,
      LucideCircleUser,
      LucideCoins,
      LucideCopy,
      LucideCreditCard,
      LucideDownload,
      LucideEllipsis,
      LucideFunnel,
      LucideGift,
      LucideHandCoins,
      LucideHeartPulse,
      LucideHouse,
      LucideInfo,
      LucideLandmark,
      LucideList,
      LucideLogOut,
      LucidePartyPopper,
      LucidePause,
      LucidePencil,
      LucidePiggyBank,
      LucidePlay,
      LucidePlus,
      LucideReceipt,
      LucideRefreshCw,
      LucideRepeat,
      LucideSearch,
      LucideSettings,
      LucideShare,
      LucideShoppingBag,
      LucideShoppingCart,
      LucideSmartphone,
      LucideSparkles,
      LucideSquarePlus,
      LucideStar,
      LucideTag,
      LucideTarget,
      LucideTrash,
      LucideTrendingDown,
      LucideTrendingUp,
      LucideTriangleAlert,
      LucideTv,
      LucideUndo2,
      LucideUpload,
      LucideWallet,
      LucideX,
    ),
  ],
  template: `<svg [lucideIcon]="name()" [size]="size()" [strokeWidth]="strokeWidth()"></svg>`,
  styles: `
    :host {
      display: inline-flex;
      flex-shrink: 0;
      line-height: 0;
    }
  `,
})
export class Icon {
  readonly name = input.required<IconName>();
  readonly size = input(20);
  readonly strokeWidth = input(2);
}
